import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

const ROOT=path.dirname(fileURLToPath(import.meta.url));
const DATA=path.join(ROOT,'poker_trainer_data');
const PORT=Number(process.env.PORT||8787);
const MAX_BYTES=1_500_000;
const ALLOWED_HOSTS=new Set(['api.github.com','raw.githubusercontent.com','github.com','zenodo.org','huggingface.co','raw.github.com']);
for(const d of ['packs','bots','models','sources'])fs.mkdirSync(path.join(DATA,d),{recursive:true});
const json=(res,status,body)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type'});res.end(JSON.stringify(body,null,2))};
const readBody=req=>new Promise((resolve,reject)=>{let size=0,buf='';req.on('data',c=>{size+=c.length;if(size>MAX_BYTES){reject(new Error('payload too large'));req.destroy();return}buf+=c});req.on('end',()=>resolve(buf));req.on('error',reject)});
const safeName=x=>String(x||'pack').replace(/[^a-z0-9_-]+/gi,'_').slice(0,80)||'pack';
function validUrl(raw){let u;try{u=new URL(raw)}catch{return null}if(u.protocol!=='https:')return null;if(process.env.ALLOW_ANY_SOURCE!=='1'&&!ALLOWED_HOSTS.has(u.hostname))return null;return u}
function hash(value){return crypto.createHash('sha256').update(value).digest('hex').slice(0,16)}
function files(dir){return fs.readdirSync(dir).filter(x=>x.endsWith('.json')).map(x=>JSON.parse(fs.readFileSync(path.join(dir,x),'utf8')))}
function catalog(){return{packs:files(path.join(DATA,'packs')),bots:files(path.join(DATA,'bots')),models:files(path.join(DATA,'models')),sources:files(path.join(DATA,'sources'))}}
function normalize(raw,kind,source){let value=raw;if(typeof raw==='string'){try{value=JSON.parse(raw)}catch{value={raw:raw.slice(0,20000)}}}let items=value.items||value.scenarios||value.strategies||value.metrics||value.models||value.bots||value;let pack={id:`${kind}-${hash(JSON.stringify(value))}`,kind,name:value.name||value.title||`${kind} update`,version:value.version||new Date().toISOString().slice(0,10),source,updatedAt:new Date().toISOString(),items:Array.isArray(items)?items:[items],license:value.license||'unknown',quality:'unverified'};return pack}
async function fetchSource(body){let u=validUrl(body.url);if(!u)throw new Error('仅允许 HTTPS；默认只允许公开 GitHub、Zenodo、Hugging Face 源。需要其他域名时设置 ALLOW_ANY_SOURCE=1。');let ac=new AbortController(),timer=setTimeout(()=>ac.abort(),15000);try{let r=await fetch(u,{signal:ac.signal,headers:{accept:'application/json,text/plain,*/*','user-agent':'PokerTrainer-UpdateClient/1.0'}});if(!r.ok)throw new Error(`source returned ${r.status}`);let text=await r.text();if(Buffer.byteLength(text,'utf8')>MAX_BYTES)throw new Error('source too large');let pack=normalize(text,body.kind||'scenario',u.toString());let file=path.join(DATA,'packs',`${safeName(pack.id)}.json`);fs.writeFileSync(file,JSON.stringify(pack,null,2));fs.writeFileSync(path.join(DATA,'sources',`${safeName(pack.id)}.json`),JSON.stringify({url:u.toString(),kind:body.kind||'scenario',lastFetched:pack.updatedAt,packId:pack.id},null,2));return pack}finally{clearTimeout(timer)}}
function handler(req,res){if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});res.end();return}let u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/api/health')return json(res,200,{ok:true,service:'poker-trainer-update-server',port:PORT,now:new Date().toISOString(),allowedHosts:[...ALLOWED_HOSTS]});if(u.pathname==='/api/catalog'&&req.method==='GET')return json(res,200,catalog());if(u.pathname==='/api/fetch-source'&&req.method==='POST')return readBody(req).then(x=>fetchSource(JSON.parse(x))).then(pack=>json(res,200,{ok:true,pack})).catch(e=>json(res,400,{ok:false,error:e.message}));if(u.pathname==='/api/save-bot'&&req.method==='POST')return readBody(req).then(x=>{let v=JSON.parse(x);v.id=v.id||`bot-${hash(JSON.stringify(v))}`;v.updatedAt=new Date().toISOString();fs.writeFileSync(path.join(DATA,'bots',safeName(v.id)+'.json'),JSON.stringify(v,null,2));return json(res,200,{ok:true,bot:v})}).catch(e=>json(res,400,{ok:false,error:e.message}));if(u.pathname==='/api/save-model'&&req.method==='POST')return readBody(req).then(x=>{let v=JSON.parse(x);v.id=v.id||`model-${hash(JSON.stringify(v))}`;v.updatedAt=new Date().toISOString();fs.writeFileSync(path.join(DATA,'models',safeName(v.id)+'.json'),JSON.stringify(v,null,2));return json(res,200,{ok:true,model:v})}).catch(e=>json(res,400,{ok:false,error:e.message}));if(u.pathname==='/api/refresh'&&req.method==='POST')return readBody(req).then(x=>{let list=JSON.parse(x);return Promise.all((Array.isArray(list)?list:[]).map(fetchSource))}).then(packs=>json(res,200,{ok:true,packs})).catch(e=>json(res,400,{ok:false,error:e.message}));if(req.method==='GET'){let file=u.pathname==='/'?'texas_holdem_trainer.html':u.pathname.replace(/^\//,'');let target=path.resolve(ROOT,file);if(!target.startsWith(path.resolve(ROOT)))return json(res,403,{error:'forbidden'});if(!fs.existsSync(target)||fs.statSync(target).isDirectory())return json(res,404,{error:'not found'});let ext=path.extname(target),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8'};res.writeHead(200,{'content-type':types[ext]||'application/octet-stream','access-control-allow-origin':'*'});fs.createReadStream(target).pipe(res);return}json(res,404,{error:'not found'})}
async function autoRefresh(){let list=files(path.join(DATA,'sources'));for(const source of list){try{await fetchSource({url:source.url,kind:source.kind});console.log(`auto-updated ${source.url}`)}catch(e){console.warn(`auto-update failed ${source.url}: ${e.message}`)}}}
const AUTO_UPDATE_MS=Number(process.env.AUTO_UPDATE_MS||0);if(AUTO_UPDATE_MS>0){setInterval(autoRefresh,AUTO_UPDATE_MS);console.log(`Automatic refresh enabled every ${AUTO_UPDATE_MS} ms`)}
http.createServer(handler).listen(PORT,'0.0.0.0',()=>console.log(`Poker Trainer update server: http://localhost:${PORT}`));
